common:
  env: dev
  ingress:
    host: uniformen.dev.entur.no
  configmap:
    enabled: true
    data:
      ENVIRONMENT: dev
      LOG_LEVEL: info
      AUTH0_INTERNAL_AUDIENCE: https://api.dev.entur.io
      AUTH0_INTERNAL_ISSUER: https://internal.dev.entur.org/
      AUTH0_INTERNAL_JWKS_URI: https://internal.dev.entur.org/.well-known/jwks.json
      AUTH0_INTERNAL_USERINFO_URI: https://internal.dev.entur.org/userinfo
      AUTH0_PARTNER_AUDIENCE: https://api.dev.entur.io,https://portal.dev.entur.org
      AUTH0_PARTNER_ISSUER: https://partner.dev.entur.org/
      AUTH0_PARTNER_JWKS_URI: https://partner.dev.entur.org/.well-known/jwks.json
      AUTH0_PARTNER_USERINFO_URI: https://partner.dev.entur.org/userinfo
