name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    uses: entur/gha-meta/.github/workflows/release.yml@c14eef7f4d90ed1be2c1df4dfb0927322bcbb3ba # v1
    with:
      release_type: manifest
    permissions:
      contents: write
      pull-requests: write
      issues: write

  build-package:
    name: Build @entur/uniformen
    needs: [release-please]
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      artifact_name: ${{ steps.prepare-packages.outputs.artifact_name }}
    defaults:
      run:
        working-directory: packages/uniformen
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
        with:
          version: 2026.9.18
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Test
        run: bun run test
      - name: Build
        run: bun run build
      - id: prepare-packages
        uses: entur/gha-npmjs/.github/actions/prepare-packages@d1701803b89f6393047cdff568ba264b25cefd2d # v1.0.0
        with:
          release_type: manifest
          package_manager: bun

  publish-package:
    name: Publish @entur/uniformen to npm
    needs: [build-package]
    permissions:
      contents: read
      id-token: write
    uses: entur/gha-npmjs/.github/workflows/publish.yml@d1701803b89f6393047cdff568ba264b25cefd2d # v1.0.0
    with:
      artifact_name: ${{ needs.build-package.outputs.artifact_name }}
      provenance: true
